Update Jenkinsfile

diff --git a/continuous-integration-continuous-deployment/Jenkinsfile b/continuous-integration-continuous-deployment/Jenkinsfile
--- a/continuous-integration-continuous-deployment/Jenkinsfile
+++ b/continuous-integration-continuous-deployment/Jenkinsfile
@@ -40,20 +40,26 @@ pipeline {
             }
         }
 
-        stage('Building Docker Image') {
+
+    stages {
+        stage('Build Docker Image') {
             steps {
-                sh "docker build -t ${params.IMAGE_NAME}:${params.VERSION} ."
+                script {
+                    // Build your Docker image here
+                    sh 'docker build -t first-real-project-app:V0015 .'
+                }
             }
         }
 
         stage('Push To Elastic Container Registry') {
             steps {
                 script {
-                    sh """
-                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${params.ECR_URI}
-                    docker tag ${params.IMAGE_NAME}:${params.VERSION} ${params.ECR_URI}:${params.VERSION}
-                    docker push ${params.ECR_URI}:${params.VERSION}
-                    """
+                    // Log in to ECR and push the Docker image
+                    sh '''
+                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382432814.dkr.ecr.us-east-1.amazonaws.com/first-real-project
+                        docker tag first-real-project-app:V0015 992382432814.dkr.ecr.us-east-1.amazonaws.com/first-real-project:V0015
+                        docker push 992382432814.dkr.ecr.us-east-1.amazonaws.com/first-real-project:V0015
+                    '''
                 }
             }
         }
@@ -61,118 +67,46 @@ pipeline {
         stage('Check and Create Target Group') {
             steps {
                 script {
+                    def targetGroupName = 'marketvector-tg'
+                    def vpcId = '<YOUR_VPC_ID>'  // Replace with your VPC ID
+
                     // Check if the target group exists
                     def targetGroupArn = sh(script: """
-                        aws elbv2 describe-target-groups --names ${params.TARGET_GROUP_NAME} --query 'TargetGroups[0].TargetGroupArn' --output text
+                        aws elbv2 describe-target-groups --names ${targetGroupName} --query 'TargetGroups[0].TargetGroupArn' --output text || echo "None"
                     """, returnStdout: true).trim()
 
                     if (targetGroupArn == "None") {
-                        echo "Target group ${params.TARGET_GROUP_NAME} does not exist. Creating target group..."
+                        echo "Target group ${targetGroupName} does not exist. Creating target group..."
                         targetGroupArn = sh(script: """
-                            aws elbv2 create-target-group --name ${params.TARGET_GROUP_NAME} --protocol HTTP --port 8081 --vpc-id ${params.VPC_ID} --query 'TargetGroups[0].TargetGroupArn' --output text
+                            aws elbv2 create-target-group --name ${targetGroupName} --protocol HTTP --port 8081 --vpc-id ${vpcId} --query 'TargetGroups[0].TargetGroupArn' --output text
                         """, returnStdout: true).trim()
+
+                        if (targetGroupArn == "") {
+                            error "Failed to create target group."
+                        }
+
                         echo "Created Target Group ARN: ${targetGroupArn}"
                     } else {
                         echo "Using existing Target Group ARN: ${targetGroupArn}"
                     }
 
                     // Update the create service JSON with the target group ARN
-                    def createServiceJson = readFile(file: params.CREATE_SERVICE_FILE)
+                    def createServiceJson = readFile(file: 'path/to/create-ecs-service.json')
                     createServiceJson = createServiceJson.replaceAll(/"targetGroupArn": "[^"]+"/, "\"targetGroupArn\": \"${targetGroupArn}\"")
-                    writeFile(file: params.CREATE_SERVICE_FILE, text: createServiceJson)
+                    writeFile(file: 'path/to/create-ecs-service.json', text: createServiceJson)
                 }
             }
         }
 
-        stage('Register Task Definition') {
-            steps {
-                script {
-                    def taskDefArn = sh(script: """
-                        aws ecs register-task-definition --cli-input-json file://${params.TASK_DEF_JSON} --query 'taskDefinition.taskDefinitionArn' --output text
-                    """, returnStdout: true).trim()
-                    echo "Registered Task Definition ARN: ${taskDefArn}"
-
-                    // Update the update service JSON with the task definition ARN
-                    def updateServiceJson = readFile(file: params.UPDATE_SERVICE_FILE)
-                    updateServiceJson = updateServiceJson.replaceAll(/"taskDefinition": "arn:aws:ecs:[^"]+"/, "\"taskDefinition\": \"${taskDefArn}\"")
-                    writeFile(file: params.UPDATE_SERVICE_FILE, text: updateServiceJson)
-                }
-            }
-        }
-
-        stage('Stop all running tasks') {
-            steps {
-                script {
-                    def serviceExists = sh(script: """
-                        aws ecs describe-services --cluster ${params.ECS_CLUSTER_NAME} --services ${params.SERVICE_NAME} --query "services[?status=='ACTIVE'].[serviceName]" --output text
-                    """, returnStdout: true).trim()
-
-                    if (serviceExists) {
-                        echo "Stopping running tasks for service ${params.SERVICE_NAME}..."
-                        sh """
-                        tasks=\$(aws ecs list-tasks --cluster ${params.ECS_CLUSTER_NAME} --service-name ${params.SERVICE_NAME} --desired-status RUNNING --query taskArns --output text)
-                        for task in \$tasks; do
-                            aws ecs stop-task --cluster ${params.ECS_CLUSTER_NAME} --task \$task
-                        done
-                        """
-                    } else {
-                        echo "Service ${params.SERVICE_NAME} does not exist. Skipping stop tasks step."
-                    }
-                }
-            }
-        }
-
-        stage('Wait for Tasks to Stop') {
-            steps {
-                script {
-                    def serviceExists = sh(script: """
-                        aws ecs describe-services --cluster ${params.ECS_CLUSTER_NAME} --services ${params.SERVICE_NAME} --query "services[?status=='ACTIVE'].[serviceName]" --output text
-                    """, returnStdout: true).trim()
-
-                    if (serviceExists) {
-                        echo "Waiting for tasks to stop for service ${params.SERVICE_NAME}..."
-                        timeout(time: 5, unit: 'MINUTES') {
-                            waitUntil {
-                                def tasks = sh(script: """
-                                    aws ecs list-tasks --cluster ${params.ECS_CLUSTER_NAME} --service-name ${params.SERVICE_NAME} --desired-status RUNNING --query taskArns --output text
-                                """, returnStdout: true).trim()
-
-                                return tasks == null || tasks.isEmpty()
-                            }
-                        }
-                    } else {
-                        echo "Service ${params.SERVICE_NAME} does not exist. Skipping wait for tasks to stop step."
-                    }
-                }
-            }
-        }
-
-        stage('Check and Update ECS Service') {
-            steps {
-                script {
-                    def clientToken = UUID.randomUUID().toString()
-                    sh """
-                    SERVICE_EXISTS=\$(aws ecs describe-services --cluster ${params.ECS_CLUSTER_NAME} --services ${params.SERVICE_NAME} --query "services[?status=='ACTIVE'].[serviceName]" --output text)
-
-                    if [ -z "\$SERVICE_EXISTS" ]; then
-                      echo "Service ${params.SERVICE_NAME} does not exist. Creating service..."
-                      aws ecs create-service --cli-input-json file://${params.CREATE_SERVICE_FILE} --client-token ${clientToken}
-                    else
-                      echo "Service ${params.SERVICE_NAME} exists. Updating service..."
-                      aws ecs update-service --cli-input-json file://${params.UPDATE_SERVICE_FILE}
-                    fi
-                    """
-                }
-            }
-        }
+        // Add your other stages here (Register Task Definition, Stop all running tasks, etc.)
     }
 
     post {
         always {
-            echo 'Pipeline completed.'
+            echo "Pipeline completed."
         }
         failure {
-            echo 'Pipeline failed.'
+            echo "Pipeline failed."
         }
     }
 }
